'.\" -*- nroff -*-
.TH KAFS-FRONT 8 "2026-03-17" "kafs 0.4.0" "System Administration"
.SH NAME
kafs-front \- hotplug front supervisor for kafs-back process
.SH SYNOPSIS
.B kafs-front
.RB [ -h | --help ]
.SH DESCRIPTION
.B kafs-front
manages lifecycle of
.BR kafs-back (8)
for hotplug mode.
It performs handshake/session restore and restarts back process when requested.
.SH OPTIONS
.TP
.BR -h ", " --help
Show help and exit.
.SH SEE ALSO
.BR kafs (1),
.BR kafsctl (1),
.BR kafs-back (8)
.SH AUTHOR
kafs project.
