name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps (system)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libfuse3-dev pkg-config clang-format cppcheck python3-pip jq

      - name: Setup Node.js for jscpd
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Autotools bootstrap
        run: |
          autoreconf -fi
          ./configure

      - name: Build
        run: make -j2

      - name: Unit tests
        run: make check -j2

      - name: Formatting check (clang-format)
        run: ./scripts/format.sh

      - name: Lint
        run: ./scripts/lint.sh

      - name: Clone detection (jscpd)
        run: ./scripts/clones.sh

      - name: Dead code (cppcheck)
        run: ./scripts/deadcode.sh

      - name: Complexity (lizard)
        run: ./scripts/complexity.sh || true

      - name: Archive reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            report/
            src/*.log
            src/*.trs
